### ISSUE TITLE
Outlook 2013

### ISSUE THREAD

**Issue by StyvieK** [BradlySharpe/trelloOutlookAddon#1]
Hi, 

I have installed this in OUtlook 2013.  

The add-on is listed and valid but does not show up ?  How do I activate or get the Add-In to display ? 

Thanks, 
Steve

**Comment by BradlySharpe** [comment]
Hi Steve,

Do you have the Trello menu under the File menu? You will have to click the Authorise button and authorise the application. After that if you go to your calendars in the top pane there should be a Trello Actions pane. Click on configure and select the boards you want to "pull", once you have completed the configuration, click Sync to pull new cards/refresh cards that have already been pulled. 

At the moment you have to manually start the Sync process, I am working on a background task to start syncing at a predetermined interval.

Also no updates on the appointment items in Outlook will be pushed to Trello, I am working on this also.

**Comment by StyvieK** [comment]
Hi,

I dont have a Trello menu on my file menu. 

![image](https://f.cloud.github.com/assets/2724634/1928186/ce515d0c-7e77-11e3-855f-f43417bc504c.png)

I can see it in my add-ins though. 

![image](https://f.cloud.github.com/assets/2724634/1928190/e90f5e28-7e77-11e3-9b60-100f072d45f4.png)

Any thoughts ?

**Comment by BradlySharpe** [comment]
See the Trello option on the bottom of the dark blue panel on the left hand side?

If you can suggest any improvements I would appreciate it!

**Comment by StyvieK** [comment]
Thanks..  :)  not sure why I never saw it. 

Configured now.  Will let you know how it goes.

**Comment by BradlySharpe** [comment]
Thanks, there is a new version that will sync automatically behind the scenes, if you don't want it to, set the timer to 0. The previous version you have to click the sync button to manually pull the data
