### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by retorquere** [BradlySharpe/trelloOutlookAddon#2]
The link to http://mytms.at/trellooutlookaddon.zip gives a 404 error

**Comment by BradlySharpe** [comment]
Sorry I am having trouble with my host, its supposed to autorenew howver they cancelled my domain instead - good news is, that was not my primary domain.

The latest version and any information on pending releases can be found here
http://www.tailormadesolutions.com.au/trello-outlook-calendar-addon/

**Comment by BradlySharpe** [comment]
I will update the download link to reflect this also

**Comment by retorquere** [comment]
That's where I found the download link.

**Comment by BradlySharpe** [comment]
Yes but I have moved the files from my other domain to this one and updated all the download links to now point locally.

If you have any problems using the new download links, let me know!

**Comment by alclary** [comment]
I can no longer find download links at:
http://www.tailormadesolutions.com.au/trello-outlook-calendar-addon/

Do you still have any of the binary installation files for the addon? If so, could I bother you for one. I would really like to use your addon as-is. Thank you!
